CloudHRMS/Controllers/DepartmentController.cs
using CloudHRMS.Models.ViewModels;
using CloudHRMS.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CloudHRMS.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService _departmentService;

        public DepartmentController(IDepartmentService departmentService)
        {
            _departmentService = departmentService;
        }
        public IActionResult List()
        {
            IEnumerable<DepartmentViewModel> departments = _departmentService.GetAll();
            return View(departments);
        }

        [Authorize(Roles = "HR")]
        public IActionResult Edit(string id)
        {
            return View(_departmentService.GetById(id));
        }
        [Authorize(Roles = "HR")]
        public IActionResult Delete(string id)
        {
            try
            {
                _departmentService.Delete(id);
                TempData["Info"] = "Delete Successfully";
            }
            catch (Exception ex)
            {
                TempData["Info"] = "Error Occur When Deleting";
            }

            return RedirectToAction("List");
        }
        [Authorize(Roles = "HR")]
        public IActionResult Entry() => View();
        [Authorize(Roles = "HR")]
        [HttpPost]
        public IActionResult Entry(DepartmentViewModel ui)
        {
            try
            {
                //validation for existing codes
                var isAlreadyExist = _departmentService.IsAlreadyExist(ui);
                if (isAlreadyExist)
                {
                    ViewData["Info"] = "This Position code or name is already exist in the system.";
                    ViewData["Status"] = false;
                    return View(ui);
                }
                _departmentService.Create(ui);
                ViewData["Info"] = "Successfully save the recrod to the system.";
                ViewData["Status"] = true;
            }
            catch (Exception e)
            {
                ViewData["Info"] = "Error occur when the recrod save to the system." + e.Message;
                ViewData["Status"] = false;
            }
            return View();
        }

        public IActionResult Update(DepartmentViewModel departmentViewModel)
        {
            try
            {
                //Data Exchange from view Model to Entity
                //ViewModels to Data Models
                var isAlreadyExist = _departmentService.IsAlreadyExist(departmentViewModel);
                if (isAlreadyExist)
                {
                    return View("Edit", departmentViewModel);
                }
                _departmentService.Update(departmentViewModel);
                TempData["Info"] = "Successfully update the record to the system.";
                TempData["Status"] = true;
            }
            catch (Exception e)
            {
                TempData["Info"] = "Error occur when the record update to the system." + e.Message;
                TempData["Status"] = false;
                return View("Edit", departmentViewModel);
            }
            return RedirectToAction("List");//when update success go to List View
        }
    }
}

CloudHRMS/Controllers/EmployeeController.cs
using CloudHRMS.Models.ViewModels;
using CloudHRMS.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CloudHRMS.Controllers;

public class EmployeeController : Controller
{
    private readonly IEmployeeService _employeeService;

    public EmployeeController(IEmployeeService employeeService)
    {
        _employeeService = employeeService;
    }


    [Authorize(Roles = "HR")]
    public IActionResult Entry()
    {
        ViewBag.Positions = _employeeService.bindPositionData();
        ViewBag.Departmetns = _employeeService.bindDepartmentData();
        return View();
    }
    [Authorize(Roles = "HR")]
    [HttpPost]
    public IActionResult Entry(EmployeeViewModel ui)
    {
        try
        {
            var isAlreadyExist = _employeeService.IsAlreadyExist(ui);
            if (isAlreadyExist)
            {
                ViewData["Info"] = "This Position code or name is already exist in the system.";
                ViewData["Status"] = false;
                return View(ui);
            }
            _employeeService.Create(ui);
            ViewData["Info"] = "Successfully save the recrod to the system.";
            ViewData["Status"] = true;
        }
        catch (Exception e)
        {
            ViewData["Info"] = "Error occur when the record save to the system." + e.Message;
            ViewData["Status"] = false;
        }
        ViewBag.Positions = _employeeService.bindPositionData();
        ViewBag.Departments = _employeeService.bindDepartmentData();
        return View();
    }

    public IActionResult List() => View(_employeeService.GetAll());

    [Authorize(Roles = "HR")]
    public IActionResult Edit(string id)
    {
        EmployeeViewModel employeeView = _employeeService.GetById(id);
        _employeeService.bindDepartmentData();
        _employeeService.bindPositionData();
        return View(employeeView);
    }

    [HttpPost]
    public IActionResult Update(EmployeeViewModel employeeViewModel)
    {
        try
        {
            //Data Exchange from view Model to Entity
            //ViewModels to Data Models
            var isAlreadyExist = _employeeService.IsAlreadyExist(employeeViewModel);
            if (isAlreadyExist)
            {
                return View("Edit", employeeViewModel);
            }
            _employeeService.Update(employeeViewModel);
            TempData["Info"] = "Successfully update the record to the system.";
            TempData["Status"] = true;
        }
        catch (Exception e)
        {
            ViewData["Info"] = "Error occur when the record update to the system." + e.Message;
            ViewData["Status"] = false;
        }
        return RedirectToAction("List");
    }

    public IActionResult Delete(string id)
    {
        try
        {
            _employeeService.Delete(id);
            TempData["Info"] = "Delete Successfully";
        }
        catch (Exception e)
        {
            TempData["Info"] = "Error occur when delete the record." + e.Message;
        }
        return RedirectToAction("List");
    }
}

CloudHRMS/Controllers/PayrollController.cs
using CloudHRMS.DAO;
using CloudHRMS.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CloudHRMS.Controllers
{
    public class PayrollController : Controller
    {
        private readonly CloudHRMSApplicationDbContext _cloudHRMSApplicationDbContext;

        public PayrollController(CloudHRMSApplicationDbContext cloudHRMSApplicationDbContext)
        {
            _cloudHRMSApplicationDbContext = cloudHRMSApplicationDbContext;
        }

        private void bindDepartmentData()
        {
            IList<DepartmentViewModel> departments = _cloudHRMSApplicationDbContext.Departments.Where(w => !w.IsInActive).Select(s =>
            new DepartmentViewModel
            {
                Id = s.Id,
                Code = s.Code + "/" + s.Name
            }).ToList();
            ViewBag.Departments = departments;
        }
        private void bindEmployeeData()
        {
            IList<EmployeeViewModel> employees = _cloudHRMSApplicationDbContext.Employees.Where(w => !w.IsInActive).Select(s =>
            new EmployeeViewModel
            {
                Id = s.Id,
                Code = s.Code + "/" + s.Name
            }).ToList();
            ViewBag.Employees = employees;
        }
        public IActionResult PayrollProcess()
        {
            bindEmployeeData();
            bindDepartmentData();
            return View();
        }

        public IActionResult PayrollReport()
        {
            return View();
        }
    }
}

CloudHRMS/Controllers/PositionController.cs
using CloudHRMS.DAO;
using CloudHRMS.Models.Entities;
using CloudHRMS.Models.ViewModels;
using CloudHRMS.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace CloudHRMS.Controllers
{
    public class PositionController : Controller
    {
        private readonly IPositionService _positionService;

        //constructor injection for ApplicationDbContext
        public PositionController(IPositionService positionService)
        {
            _positionService = positionService;
        }
        public IActionResult Entry()
        {
            PositionViewModel positionViewModel = new PositionViewModel()
            {
                Level = 1
            };
            return View(positionViewModel);
        }
        [HttpPost]
        public IActionResult Entry(PositionViewModel positionViewModel)
        {
            try
            {

                var isAlreadyExist = _positionService.IsAlreadyExist(positionViewModel);
                if (isAlreadyExist)
                {
                    ViewData["Info"] = "The Position is already exit.";
                    ViewData["Status"] = false;
                    return View(positionViewModel);
                }
                _positionService.Create(positionViewModel);
                ViewData["Info"] = "Successfully save the record to the system.";
                ViewData["Status"] = true;
            }
            catch (Exception e)
            {
                ViewData["Info"] = "Error occur when the record save to the system."+e.Message;
                ViewData["Status"] = false;
            }
            return View(positionViewModel);
        }
        public IActionResult List()
        {
            var positions = _positionService.GetAll();
            return View(positions);
        }
        public IActionResult Edit(string id)
        {
            PositionViewModel positionViewModel = _positionService.GetById(id);
            return View(positionViewModel);
        }
        [HttpPost]
        public IActionResult Update(PositionViewModel positionViewModel)
        {
            try
            {
                //Data Exchange from view Model to Entity
                //ViewModels to Data Models
                var isAlreadyExist = _positionService.IsAlreadyExist(positionViewModel);
                if (isAlreadyExist)
                {
                    return View("Edit", positionViewModel);
                }
                _positionService.Update(positionViewModel);
                TempData["Info"] = "Successfully update the record to the system.";
                TempData["Status"] = true;
            }
            catch (Exception e)
            {
                TempData["Info"] = "Error occur when the record update to the system." + e.Message;
                TempData["Status"] = false;
                return View("Edit", positionViewModel);
            }
            return RedirectToAction("List");//when update success go to List View
        }
        public IActionResult Delete(string id)
        {
            try
            {
                var status = _positionService.Delete(id);
                TempData["Info"] = "Successfully delete";
                TempData["Status"] = false;
            }
            catch (Exception e)
            {
                TempData["info"] = "Error occur when delete the record."+e.Message;
                TempData["Status"] = false;
            }
            return RedirectToAction("List");//when delete success go to List View
        }
    }
}

CloudHRMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CloudHRMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CloudHRMS.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CloudHRMS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown text-dark">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Position
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Position" asp-action="List">List</a></li>
                                </ul>
                            </li>       
                            <li class="nav-item dropdown text-dark">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Department
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Department" asp-action="List">List</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown text-dark">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Employee
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Employee" asp-action="Index">List</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown text-dark">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Attendance Policy
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="AttendancePolicy" asp-action="List">List</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown text-dark">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    My Shift Assign
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="ShiftAssign" asp-action="List">List</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown text-dark">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    My  Daily Attendance
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="DailyAttendance" asp-action="List">List</a></li>
                                </ul>
                            </li>          
                            <li class="nav-item dropdown text-dark">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    My Attendance
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="AttendanceMaster" asp-action="List">List</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown text-dark">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    My Pay History
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Payroll" asp-action="List">List</a></li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item">
                          <partial name="_LoginPartial" />
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CloudHRMS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>